<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" xmlns:ng="http://angularjs.org"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" xmlns:ng="http://angularjs.org"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" xmlns:ng="http://angularjs.org"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" xmlns:ng="http://angularjs.org"> <!--<![endif]-->
<head>
    <base href="/backend/modules/content-new/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="fragment" content="!" />
    <meta name="viewport" content="width=device-width">
    <?=$this->headTitle() . PHP_EOL?>
    <?=$this->headMeta() . PHP_EOL?>

    <link rel="shortcut icon" href="/modules/shift-kernel/img/backend/favicon.ico" />
    <link href="/modules/shift-kernel/css/backend.css" media="screen" rel="stylesheet" type="text/css" />
    <?php echo $this->render('shiftcontent-new.grunt.styles');?>

</head>
<body id="ng-app" ng-app="shiftContentApp">

  <?=$this->render('shiftkernel/backend/toolbar')?>

  <?php echo $this->render('shiftcontent-new.grunt.shell');?>
  <?php echo $this->render('shiftcontent-new.grunt.scripts');?>


  <script type="text/javascript" src="/modules/shift-kernel/js/backend.min.js"></script>
  <?=$this->headScript() . PHP_EOL?>
</body>
</html>
