<?php

namespace ShiftContentNewMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130821061330 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE shiftcontentnew_field_settings (id INT AUTO_INCREMENT NOT NULL, fieldId INT DEFAULT NULL, field VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8F428EB15E697A44 (fieldId), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_field_settings_file (id INT NOT NULL, destination VARCHAR(255) NOT NULL, mode VARCHAR(255) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_item_properties (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, itemId INT DEFAULT NULL, valueType VARCHAR(255) NOT NULL, stringValue VARCHAR(255) DEFAULT NULL, textValue LONGTEXT DEFAULT NULL, dateValue DATETIME DEFAULT NULL, mediaItem INT DEFAULT NULL, mediaAlbum INT DEFAULT NULL, INDEX IDX_88732D4CB5F8B771 (itemId), INDEX IDX_88732D4CB913E127 (mediaItem), INDEX IDX_88732D4C663BEE8F (mediaAlbum), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_items (id INT AUTO_INCREMENT NOT NULL, status VARCHAR(255) NOT NULL, created DATETIME NOT NULL, publicationDate DATETIME NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, authorId INT DEFAULT NULL, contentTypeId INT DEFAULT NULL, UNIQUE INDEX UNIQ_6288CFC0989D9B62 (slug), UNIQUE INDEX UNIQ_6288CFC0A196F9FD (authorId), UNIQUE INDEX UNIQ_6288CFC0FDA329E8 (contentTypeId), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_type_field_attributes (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, className VARCHAR(255) NOT NULL, fieldId INT DEFAULT NULL, INDEX IDX_94A7E2595E697A44 (fieldId), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_type_field_attribute_options (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, variable VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, attributeId INT DEFAULT NULL, INDEX IDX_6308AE06ED407E17 (attributeId), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_type_fields (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, property VARCHAR(255) NOT NULL, fieldType VARCHAR(255) NOT NULL, typeId INT DEFAULT NULL, UNIQUE INDEX UNIQ_CAC54EB35E237E06 (name), UNIQUE INDEX UNIQ_CAC54EB38BF21CDE (property), INDEX IDX_CAC54EB39BF49490 (typeId), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("CREATE TABLE shiftcontentnew_types (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_DAA6AFBD5E237E06 (name), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE shiftcontentnew_field_settings ADD CONSTRAINT FK_8F428EB15E697A44 FOREIGN KEY (fieldId) REFERENCES shiftcontentnew_type_fields (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_field_settings_file ADD CONSTRAINT FK_3E9E7B8DBF396750 FOREIGN KEY (id) REFERENCES shiftcontentnew_field_settings (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE shiftcontentnew_item_properties ADD CONSTRAINT FK_88732D4CB5F8B771 FOREIGN KEY (itemId) REFERENCES shiftcontentnew_items (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_item_properties ADD CONSTRAINT FK_88732D4CB913E127 FOREIGN KEY (mediaItem) REFERENCES shiftmedia_items (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_item_properties ADD CONSTRAINT FK_88732D4C663BEE8F FOREIGN KEY (mediaAlbum) REFERENCES shiftmedia_albums (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_items ADD CONSTRAINT FK_6288CFC0A196F9FD FOREIGN KEY (authorId) REFERENCES shiftuser (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_items ADD CONSTRAINT FK_6288CFC0FDA329E8 FOREIGN KEY (contentTypeId) REFERENCES shiftcontentnew_types (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_type_field_attributes ADD CONSTRAINT FK_94A7E2595E697A44 FOREIGN KEY (fieldId) REFERENCES shiftcontentnew_type_fields (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_type_field_attribute_options ADD CONSTRAINT FK_6308AE06ED407E17 FOREIGN KEY (attributeId) REFERENCES shiftcontentnew_type_field_attributes (id)");
        $this->addSql("ALTER TABLE shiftcontentnew_type_fields ADD CONSTRAINT FK_CAC54EB39BF49490 FOREIGN KEY (typeId) REFERENCES shiftcontentnew_types (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE shiftcontentnew_field_settings_file DROP FOREIGN KEY FK_3E9E7B8DBF396750");
        $this->addSql("ALTER TABLE shiftcontentnew_item_properties DROP FOREIGN KEY FK_88732D4CB5F8B771");
        $this->addSql("ALTER TABLE shiftcontentnew_type_field_attribute_options DROP FOREIGN KEY FK_6308AE06ED407E17");
        $this->addSql("ALTER TABLE shiftcontentnew_field_settings DROP FOREIGN KEY FK_8F428EB15E697A44");
        $this->addSql("ALTER TABLE shiftcontentnew_type_field_attributes DROP FOREIGN KEY FK_94A7E2595E697A44");
        $this->addSql("ALTER TABLE shiftcontentnew_items DROP FOREIGN KEY FK_6288CFC0FDA329E8");
        $this->addSql("ALTER TABLE shiftcontentnew_type_fields DROP FOREIGN KEY FK_CAC54EB39BF49490");
        $this->addSql("DROP TABLE shiftcontentnew_field_settings");
        $this->addSql("DROP TABLE shiftcontentnew_field_settings_file");
        $this->addSql("DROP TABLE shiftcontentnew_item_properties");
        $this->addSql("DROP TABLE shiftcontentnew_items");
        $this->addSql("DROP TABLE shiftcontentnew_type_field_attributes");
        $this->addSql("DROP TABLE shiftcontentnew_type_field_attribute_options");
        $this->addSql("DROP TABLE shiftcontentnew_type_fields");
        $this->addSql("DROP TABLE shiftcontentnew_types");
    }
}
