<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <?=$this->headTitle() . PHP_EOL?>
    <?=$this->headMeta() . PHP_EOL?>

    <link rel="shortcut icon" href="/modules/shift-kernel/img/backend/favicon.ico" />
    <link href="/modules/shift-kernel/css/backend.css" media="screen" rel="stylesheet" type="text/css" />
    <?php echo $this->render('shiftcontent-new.grunt.styles');?>

</head>
  <body ng-app="shiftContentApp">

    <!--[if lt IE 7]>
      <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
    <![endif]-->

    <!--[if lt IE 9]>
      <script src="/modules/shift-yeoman/components/es5-shim/es5-shim.js"></script>
      <script src="/modules/shift-yeoman/components/json3/lib/json3.min.js"></script>
    <![endif]-->

    <?=$this->render('shiftkernel/backend/toolbar')?>

    <!-- Growl notifications -->
    <div class="growlContainer">
      <div id="growlContainer"></div>
    </div>
    <!-- /Growl notifications -->

    <!-- Breadcrumbs -->
    <div shift-breadcrumbs></div>
    <!-- /Breadcrumbs -->

    <!-- Application content -->
    <table class="layoutHolder">
      <tr>
        <td class="navigation">
            <div shift-navigation></div>
        </td>
        <td class="page"><div class="content" ng-view=""></div></td>
      </tr>
    </table>
    <!-- /Application content -->




    <?php echo $this->render('shiftcontent-new.grunt.scripts');?>
    <script type="text/javascript" src="/modules/shift-kernel/js/backend.min.js"></script>
    <?=$this->headScript() . PHP_EOL?>
</body>
</html>
